### ISSUE TITLE
worker

### ISSUE THREAD

**Issue by pavelbezpravel** [moevm/MSE-2023-image-ecology-12#11]

**Comment by youngwow** [comment]
Worker должен уметь:
1. Взять из базы данных GeoTiff файл
2. Провести анализ снимка.
3. Написать отчёт в базу данных.

Все шаги должны выполняться последовательно.

**Comment by youngwow** [comment]
Перенёс в другую таску с инициализацией сервера. Там находится инициализация worker'а.

**Comment by vladDotH** [comment]
думаю что это выполнено
