### ISSUE TITLE
Рисерч возможности исправления нейросетевой модели определения лесов и оптимизации

### ISSUE THREAD

**Issue by pavelbezpravel** [moevm/MSE-2023-image-ecology-12#120]

**Comment by Saprigenie** [comment]
Было произведено исследование тестового датасета и сделаны выводы, что у тестовых изображений одинаковое пространственное разрешение и расцветка, поэтому были сделаны попытки предсказания модели на реальных данных с:
1. Таким же пространственным разрешением (10 на 10 метров 1 пиксель). Однако успеха это не принесло.
2. На изображениях с измененной яркостью и насыщенностью. Однако и здесь результат достигнут не был.

В соответствии с этим приходится предполагать, что модель плохо подготовлена к реальным данным, загружаемым в проект.
