### ISSUE TITLE
Детектор для определения южных опушек леса

### ISSUE THREAD

**Issue by zmm** [moevm/MSE-2023-image-ecology-12#176]

**Comment by youngwow** [comment]
Находить южные границы лесов. Применить таблицы углов: по каким углам светит лучше. Использовать карту высот: перспективные места - склоны

Размещать зоны с точки зрения перспективности; Поиск маршрутов к этому месту.

**Comment by youngwow** [comment]
Опушка +-20 (N) метров в лесу (5 метров внутрь леса, 5 метров снаружи).
Южная: +- 15 градусов от направления на юг

Смотреть юг, границы юга, разбить эти границы на сегменты.
