### ISSUE TITLE
Нахождение лесов на снимке

### ISSUE THREAD

**Issue by pavelbezpravel** [moevm/MSE-2023-image-ecology-12#33]

**Comment by youngwow** [comment]
Что сделано:
1. Преобразование GeoTiff снимка в 16-bit RGB Colour Image
2. Вывод всей информации из GeoTiff файла
3. Применение Method Otsu
4. Обведение контуров вокруг леса
5. Применение Connected Component Analysis
6. Бинарная классификация (изображен ли лес на снимке?) с помощью NDVI

**Comment by youngwow** [comment]
Все изменения находятся на research ветке
