### ISSUE TITLE
Нахождение дорог на снимке

### ISSUE THREAD

**Issue by pavelbezpravel** [moevm/MSE-2023-image-ecology-12#37]
Уточнить у Марка Марковича статус

**Comment by youngwow** [comment]
Статус: переименовать задачу можно

**Comment by youngwow** [comment]
Применить трансформер https://www.kaggle.com/code/balraj98/road-extraction-from-satellite-images-deeplabv3

**Comment by youngwow** [comment]
Сделано:

1. Применён трансформер DeepLab3+ с kaggle
2. В качестве альтернативного варианта был сделан edge detection c помощью алгоритма Canny следующим образом:
3. Применение фильтра Canny Edge с L2Gradient = True
4. Применением преобразование Хафа для поиска линий (т.к. мы считаем, что заросшие просеки/дороги это прямые линии)
5. Рисуем обнаруженные линии дороги на изображении

Был также протестирован Оператор Собеля, но детектор границ Кэнни представляет собой более сложный метод, который включает в себя несколько этапов обработки, включая оператор собеля:

1. Подавление шума с помощью размытия по Гауссу
2. Обнаружение краев с помощью оператора Собеля
3. non-maximum suppression
4. hysteresis thresholding
5. edge tracking by connectivity.

Результатом является более точное и надежное обнаружение краев, менее подверженное влиянию шума и создающее более тонкие края.

**Comment by youngwow** [comment]
@pavelbezpravel Описание того, что сделал.

**Comment by pavelbezpravel** [comment]
> @pavelbezpravel Описание того, что сделал.

spasibo!
