### ISSUE TITLE
Соблюсти сбалансированность датасета

### ISSUE THREAD

**Issue by pavelbezpravel** [moevm/MSE-2023-image-ecology-12#55]

**Comment by youngwow** [comment]
Что сделано:
+ соблюдено сбалансированность датасета (с помощью Class Weight Binary entropy loss function)
+ Обучена модель с data augmentation
Модель хранится в папке models -> weights
+ Добавлены графики loss, precision, recall, prc и Confusion matrix
+ протестировано на тестовом датасете с изображениями 512x512
