### ISSUE TITLE
Инициализация сервера и worker'а

### ISSUE THREAD

**Issue by vladDotH** [moevm/MSE-2023-image-ecology-12#7]
Роутер/гейтвей, веб-бекенд, загрузка/выгрузка файлов

**Comment by youngwow** [comment]
Worker должен уметь:

1. Взять из базы данных GeoTiff файл
2. Провести анализ снимка.
3. Написать отчёт в базу данных.
Все шаги должны выполняться последовательно.

Необходимо сделать инициализацию worker'а.

**Comment by youngwow** [comment]
По worker'у:

Был реализован метод Оцу: он включает в себя преобразование изображения в двоичный формат, где пиксели классифицируются как («полезные» и «фоновые»), рассчитывая такой порог, чтобы внутриклассовая дисперсия была минимальной. Далее убрал шум с помощью морфологических операций и выделил контуры леса.
