### ISSUE TITLE
Записывать тайлы в память

### ISSUE THREAD

**Issue by pavelbezpravel** [moevm/MSE-2023-image-ecology-12#91]
Сократить количество записей в ФС временных файлов

**Comment by Saprigenie** [comment]
Эту задачу, связанную с размещением тайлов в оперативной памяти, а не в файловой системе, не стоит выполнять так как:
а) Оперативной памяти  может не хватать, если 2-12 воркеров (по числу ядер) начнут записывать в оперативную память tiff-ы, которые размером приблизительно 1 Гб.
б) Сама функция gdal2tiles использует для записи доп. данных стандартную библиотеку питона по работе с файлами, например:
with open(path) as f:
f.write("something")
, что означает, что виртуальная файловая система gdal-а работать с ними не будет.
в) Можно сами тайлы перехватывать и записывать в виртуальную память с помощью костылей с переопределением функций у базовых классов gdal-а (пример в коде снизу) на время, но см. пункт а) почему это плохая идея
г) Была еще идея тайлы сразу записывать в бд, но тут то же проблема, так как 2 этапа, которые существуют в генерации тайлов (Generating Base Tiles и Generating Overview Tiles) взаимосвязанны, т.е. сначала в Generating Base Tiles нарезается базовое изображение на фрагменты, а потом в Generating Overview Tiles используются уже нарезанные кусочки для создания увеличенных копий на разных приближениях для карты. Так что, если даже переопределить функции на запись в бд, то на втором этапе Generating Overview Tiles придется переопределить еще пару функций, чтобы они брали тайлы из бд. Но при этом возникнет ситуация, когда во время нарезки наша бд будет получать тысячи запросов к ней ежесекундно, что очень негативно скажется на работе всего проекта в целом.
```
from osgeo import gdal
import gdal2tiles

def CreateCopy(self, *args, **kwargs):
    # args[0] = path, args[1] = Dataset to write.
    if (args[0].endswith('.png')):
        pass
    else:
        return self.CreateCopyReal(*args, **kwargs)

gdal.Driver.CreateCopyReal = gdal.Driver.CreateCopy
gdal.Driver.CreateCopy = CreateCopy
gdal2tiles.generate_tiles('1.tif', './out')
```
